name: russian_hat
description: Team based game for a funny company.

version: 2.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.3.3
  rxdart: ^0.21.0
  audioplayers: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 
  assets:
   - res/
   - assets/
